### ISSUE TITLE
'앨범이 너무 멀리있습니다' 알림 

### ISSUE THREAD

**Issue by chancehee** [nekarak8s/gallery#97]
가까이에서 앨범을 조준해도 알림이 나옵니다.
(알림은 나오지만, 앨범은 열림)

<img width="1223" alt="스크린샷 2024-01-21 오후 3 53 01" src="https://github.com/nekarak8s/gallery/assets/59447235/36835436-311b-4a75-9d98-354094a329a5">

**Comment by Byongho96** [comment]
착시현상입니다

**Comment by Byongho96** [comment]
그리고 무슨 이미지가 3.2MB이나요?? 데이터 낭-비입니다
